{% set version = "0.2.6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-set6
  version: {{ version|replace("-", "_") }}

source:
  url: https://raphaels1.r-universe.dev/src/contrib/set6_{{ version }}.tar.gz
  sha256: e15fa580a3eb2f8284de84fb46f1ffbaf35e61826fbde791ae1165161ca9428e

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-r6
    - r-rcpp
    - r-checkmate
    - r-ooplah
  run:
    - r-base
    - r-r6
    - r-rcpp
    - r-checkmate
    - r-ooplah

test:
  commands:
    - $R -e "library('set6')"           # [not win]
    - "\"%R%\" -e \"library('set6')\""  # [win]

about:
  home: https://xoopR.github.io/set6/
  dev_url: https://github.com/xoopR/set6
  license: MIT
  summary: An object-oriented package for mathematical sets, upgrading the current gold-standard {sets}. Many forms of mathematical sets are implemented, including (countably finite) sets, tuples, intervals (countably infinite or uncountable), and fuzzy variants. Wrappers extend functionality by allowing symbolic representations
    of complex operations on sets, including unions, (cartesian) products, exponentiation, and differences (asymmetric and symmetric).
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - pascal-git
